package com.cf.taskmaster;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "taskmaster")
public class Task {

    private UUID id;
    private String title;
    private String description;
    private String assignee;
    private String status = "Available";
    private String imageUrl = "https://stephenc-task-master-images.s3-us-west-2.amazonaws.com/1562699691733-avatar-placeholder.jpg";

    public Task() {}

    public void incrementStatus() {
        if (this.getStatus().equals("Available"))
            this.setStatus("Assigned");
        else if (this.getStatus().equals("Assigned"))
            this.setStatus("Accepted");
        else if (this.getStatus().equals("Accepted"))
            this.setStatus("Finished");
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return this.assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
        this.setStatus("Assigned");
    }
    @DynamoDBAttribute
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}
